###
POST http://localhost:9000/api/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@example.com",
  "contraseña": "123456"
}
###
POST http://localhost:9000/api/users/register HTTP/1.1
Content-Type: application/json

{
    "nombre": "adrew pezer",
    "email": "adrew_pez@example.com",
    "contraseña": "123456",
    "rol": "user"
}

###
GET http://localhost:9000/api/users/list HTTP/1.1
###
GET http://localhost:9000/api/users/670ee09497379d0ae7cda3bc/view HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTdjZjRiOGFhM2Q0NjE2ZWE2Y2IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MDk0NzI4LCJleHAiOjE3MjkwOTgzMjh9.pgjjG37Jj9JcAgMEUNHjXmBar8sNWr6V2ISEJft1N1w
###
PUT http://localhost:9000/api/users/670ee09497379d0ae7cda3bc/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTdjZjRiOGFhM2Q0NjE2ZWE2Y2IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MDk0NzI4LCJleHAiOjE3MjkwOTgzMjh9.pgjjG37Jj9JcAgMEUNHjXmBar8sNWr6V2ISEJft1N1w

{
    "nombre": "jhon D does",
    "email": "john.ddoe@example.com"
}

###
DELETE http://localhost:9000/api/users/670edb659cab2ee0afd425d6/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTA5NDk3Mzc5ZDBhZTdjZGEzYmMiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MDI4OTQ2LCJleHAiOjE3MjkwMzI1NDZ9.FTkD3LXEaaHi-6_3LIw5mR0U4KytoxxNMdmoov23VOo

###
POST http://localhost:9000/api/pets/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTdjZjRiOGFhM2Q0NjE2ZWE2Y2IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MDkyNDI2LCJleHAiOjE3MjkwOTYwMjZ9.CoJ_W71YMGDUd0MoJ1bJoCF40EmtGQwQQMrVOUENkuM

{
   "name": "laou",
  "type": "cat",
  "sex": "male",
  "breed": "comun",
  "birthdate": "2021-03-01T00:00:00Z",
  "age": 4,
  "weight": 1,
  "height": 2,
  "temperament": "friendly",
  "chipNumber": "12345673",
  "description": "Very playful cat",
  "owners": ["670fe439e4123598a7fa97fe"]
}

###
GET http://localhost:9000/api/pets/listAll HTTP/1.1

###
GET http://localhost:9000/api/pets/list HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTdjZjRiOGFhM2Q0NjE2ZWE2Y2IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MTMzNDAzLCJleHAiOjE3MjkxMzcwMDN9.u3CpqYXpDTFieQlyu2Zp0E7lv371l4P7xfqac5MOOk8
###
GET http://localhost:9000/api/pets/670f00c9f41bd3d69a6e50d9/view HTTP/1.1
Content-Type: application/json
###
PUT http://localhost:9000/api/pets/670f06d5f41bd3d69a6e50e4/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTdjZjRiOGFhM2Q0NjE2ZWE2Y2IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MDkyNDI2LCJleHAiOjE3MjkwOTYwMjZ9.CoJ_W71YMGDUd0MoJ1bJoCF40EmtGQwQQMrVOUENkuM

{
   "name": "sisifos",
  "type": "gato",
  "sex": "male",
  "breed": "comun",
  "birthdate": "2019-03-01T00:00:00Z",
  "age": 6,
  "weight": 12,
  "height": 3,
  "temperament": "friendly",
  "chipNumber": "1234563434",
  "description": "Very playful dog",
  "owners": ["670f00a5f41bd3d69a6e50d5","670ee6a74b8aa3d4616ea6b4"]
}

###
DELETE http://localhost:9000/api/pets/670f00384c18c220d8e4162b/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzBlZTdjZjRiOGFhM2Q0NjE2ZWE2Y2IiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI5MDM4MjAxLCJleHAiOjE3MjkwNDE4MDF9.BivDniDikNud6I_p3QJNh4flrT0HWxHfhIvumv--KBM
